[theme]
primaryColor = '#1a73e8'
backgroundColor = '#ffffff'
secondaryBackgroundColor = '#f0f2f6'
textColor = '#262730'

[server]
headless = true

[browser]
gatherUsageStats = false

[ui]
hideStreamlitLogo = true
